version: '3.7'
services: 
    telegraf:
        image: telegraf:latest
        container_name: telegraf-tpg
        network_mode: tpg
        ports: 
            - 8126:8126/udp
            - 9273:9273
        volumes: 
            - ./telegraf.conf:/etc/telegraf/telegraf.conf:ro
    
    prometheus:
        image: prom/prometheus:latest
        container_name: prometheus-tpg
        network_mode: tpg
        ports: 
            - 9090:9090
        volumes: 
            - ./prometheus.yml:/etc/prometheus/prometheus.yml

    grafana:
        image: grafana/grafana:latest
        container_name: grafana-tpg
        network_mode: tpg
        ports: 
            - 3000:3000
        # volumes: 
        #     - ./provisioning:/etc/grafana/provisioning

networks: 
    default:
        driver: tpg