global:
    scrape_interval: 15s
    evaluation_interval: 15s

scrape_configs:
    - job_name: 'telegraf-tpg-job'
        tls_config:
            insecure_skip_verify: true
        honor_labels: true
        metrics_path: '/prometheus'
        static_configs:
            - targets: ['telegraf-tpg:9273']