version: '3.7'
services: 
    influxdb:
        image: influxdb:latest
        container_name: influxdb-tick
        network_mode: tick
        ports: 
            - 8086:8086
        volumes: 
            - ./data/influxdb:/var/lib/influxdb

    telegraf:
        image: telegraf:latest
        container_name: telegraf-tick
        network_mode: tick
        depends_on: 
            - influxdb
        ports: 
            - 8125:8125/udp
        volumes: 
            - ./telegraf.conf:/etc/telegraf/telegraf.conf:ro

    chronograf:
        image: chronograf:latest
        container_name: chronograf-tick
        network_mode: tick
        depends_on: 
            - telegraf
        environment: 
            INFLUXDB_URL: http://influxdb-tick:8086
            KAPACITOR_URL: http://kapacitor-tick:9092
        ports: 
            - 8888:8888
        links:
            - influxdb
            - kapacitor
    
    kapacitor:
        image: kapacitor:latest
        container_name: kapacitor-tick
        network_mode: tick
        depends_on: 
            - telegraf
        environment: 
            KAPACITOR_HOSTNAME: kapacitor
            KAPACITOR_INFLUXDB_0_URLS_0: http://influxdb-tick:8086
        links: 
            - influxdb
        ports: 
            - 9093:9093
