apiVersion: 1

datasources:
    - name: Prometheus-TPG
        type: prometheus
        access: proxy
        url: http://prometheus-tpg:9090
        password:
        user:
        database:
        basicAuth: false
        basicAuthUser: 
        basicAuthPassword:
        withCredentials:
        isDefault: true
        jsonData:
            tlsAuth: false
            tlsAuthWithCACert: false
            tlsSkipVerify: true
        secureJsonData:
            tlsCACert: ""
            tlsClientCert: ""
            tlsClientKey: ""
        version: 1
        editable: true